import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import BeneficiosSection from '@/components/organisms/GrupoDeImagenes'

const inter = Inter({ subsets: ['latin'] })



const index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main>

        {/* BARRA DE NAVEGACIÓN */}
        <div></div>

        {/* INICIO */}
        <div className={styles.inicio}></div>

        {/* CLÁSICOS */}
        <div></div>

        {/* NOVEDADES */}
        <div></div>

        {/* BENEFICIOS Y LECTURA */}
        <div>
        <h2 className='h2-beneficios-lectura'>La lectura como un estilo de vida</h2>
        <section className='section-beneficios-lectura'>
          <div className='divs-beneficios-lectura'>
          <GrupoDeImagenes/>
          </div>
        </section>
        </div>


        {/* FOOTER */}
        <div></div>

      </main>
    </>
  )
}

export default index