import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React from "react";
import ShoppingCart from "../components/organisms/ShoppingCart";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* BARRA DE NAVEGACIÓN */}
        <div></div>

        {/* INICIO */}
        <div className={styles.inicio}> </div>

        {/* CLÁSICOS */}
        <div> <ShoppingCart/> </div>


        {/* NOVEDADES */}
        <div></div>

        {/* BENEFICIOS DE LECTURA */}
        <div></div>

        {/* FOOTER */}
        <div></div>

      
      </main>
    </>
  );
};

export default index;
